services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: medagent-backend
    working_dir: /src
    ports:
      - "5000:5000"
    environment:
      MODE: build   # change to "update" when needed
    volumes:
      - ../backend/src:/src
    networks:
      - backend

networks:
  backend:
    driver: bridge
