from abc import ABC, abstractmethod
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Tuple, Union

from pydantic import BaseModel, ConfigDict, Field, field_serializer, field_validator, model_validator

from app.models.common.py_object_id import PyObjectId
from app.models.tools.llm_interaction import LLMSettings
from app.models.tools.snomed_interaction import SnomedSettings


# ---- Options for reference types ----
class ReferenceType(str, Enum):
    TEXT = "text"
    IMAGE = "image"
    TABLE = "table"
    RECOMMENDATION = "recommendation"
    STATEMENT = "statement"
    METADATA = "metadata"


# ---- Shared structures ----

class GuidelineReferenceGroup(BaseModel):
    id: Optional[PyObjectId] = Field(default=None, alias="_id", description="MongoDB document ID")
    name: str = Field(description="Name of the reference group", examples=["question_dataset", "system_1"])
    is_chunking_result: bool = Field(
        default=False,
        description="Flag indicating whether this reference group was generated by the chunking service.",
    )


class ChunkingStrategy(str, Enum):
    FIXED_CHARACTERS = "fixed_characters"
    SENTENCE = "sentence"
    PARAGRAPH = "paragraph"


class GuidelineHierarchyEntry(BaseModel):
    title: str = Field(description="This hierarchy level's title (e.g., section header)")
    heading_level: int = Field(description="Depth of the heading (0=root, 1=chapter, 2=section, ...)")
    heading_number: str = Field(description="Heading number such as '4.2.1'")
    order: int = Field(default=0, description="Order of the heading in the document")
    
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
        validate_by_name=True,
        populate_by_name=True,
        json_schema_extra={
            "examples": [
                {
                    "title": "",
                    "heading_level": 0,
                    "heading_number": "",
                    "order": 0,
                },
                {
                    "title": "Introduction",
                    "heading_level": 1,
                    "heading_number": "1",
                    "order": 0,
                },
                {
                    "title": "Background",
                    "heading_level": 2,
                    "heading_number": "2.2",
                    "order": 1,
                },
            ],
        },
    )


class BoundingBox(BaseModel):
    page: int = Field(description="Page number of the bounding box (starting with first page = 1 according to typical PDF interaction")
    positions: Tuple[float, float, float, float] = Field(
        description="""x0, y0, x1, y1 coordinates of the bounding box in PDF page points
        - With (0, 0) as the top-left of the page
        - 1 point = (1/72) inch = 0.0353 cm (roughly)""",
    )
    
    @field_validator("positions", mode="before")
    @classmethod
    def coerce_positions(cls, v):
        if isinstance(v, list) and len(v) == 4:
            return tuple(v)
        return v
    
    @field_serializer("positions")
    def serialize_positions(self, positions):
        return list(positions)
    
    model_config = ConfigDict(arbitrary_types_allowed=True)


class GuidelineDocumentHierarchyEntry(BaseModel):
    hierarchy_entry: GuidelineHierarchyEntry = Field(
        description="Document structure from root to this hierarchy instance",
    )
    positions: List[BoundingBox] = Field(
        description="Bounding boxes of the hierarchy instance (all possible positions of 'belonging' text)",
    )
    
    model_config = ConfigDict(arbitrary_types_allowed=True)


class GuidelineDocumentHierarchy(BaseModel):
    guideline_id: PyObjectId = Field(description="MongoDB ID of the referenced guideline")
    document_hierarchy: List[GuidelineDocumentHierarchyEntry] = Field(
        description="All structures (headings) in hierarchy for entire document",
    )
    
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )


class GuidelineReferenceBase(BaseModel, ABC):
    id: Optional[PyObjectId] = Field(default=None, alias="_id", description="MongoDB document ID")
    reference_group_id: Optional[PyObjectId] = Field(
        default=None, description="MongoDB ID of the guideline group this reference belongs to",
    )
    guideline_id: PyObjectId = Field(description="MongoDB ID of the referenced guideline")
    type: ReferenceType = Field(description="Discriminator field that defines the reference type")
    bboxs: List[BoundingBox] = Field(
        default=[], description="Bounding boxes of the reference (all possible positions of 'belonging' text)",
    )
    document_hierarchy: List[GuidelineHierarchyEntry] = Field(
        default=[], description="Document structure from root to this reference",
    )
    note: Optional[str] = Field(default=None, description="Additional notes or comments about the reference")
    created_automatically: bool = Field(
        default=True, description="True if extracted automatically; changes to False after editing",
    )
    created_date: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when the reference was created or updated",
    )
    associated_keywords: Optional[List[str]] = Field(
        default=None, description="Keywords extracted from the contained reference (normalized to selected terms for keywords)",
    )
    
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    @abstractmethod
    def extract_content(self) -> str:
        raise NotImplementedError
    
    @abstractmethod
    def update_content(self, new_content: str) -> None:
        raise NotImplementedError


# ---- Concrete Reference Types ----

class GuidelineTextReference(GuidelineReferenceBase):
    type: Literal[ReferenceType.TEXT] = Field(
        default=ReferenceType.TEXT, description="Reference type identifier for text references",
    )
    contained_text: str = Field(
        description="The actual text content extracted from the document",
        examples=[
            "Der Begriff der Retention bezeichnet eine Position des Weisheitszahnes, bei der nach Abschluss des "
            "Wurzelwachstums die Okklusionsebene nicht erreicht wird.",
        ],
    )
    
    def extract_content(self) -> str:
        return self.contained_text
    
    def update_content(self, new_content: str) -> None:
        self.contained_text = new_content
        self.created_automatically = False
        self.created_date = datetime.now(timezone.utc)


class GuidelineImageReference(GuidelineReferenceBase):
    type: Literal[ReferenceType.IMAGE] = Field(
        default=ReferenceType.IMAGE, description="Reference type identifier for image references",
    )
    caption: str = Field(
        default="", description="Caption text associated with the image", examples=["Image 1: ..."],
    )
    describing_text: Optional[str] = Field(default=None, description="Additional text describing the image (optional)")
    
    def extract_content(self) -> str:
        return (f"{self.caption}: " if self.caption else "") + self.describing_text or ""
    
    def update_content(self, new_content: str) -> None:
        self.caption = new_content
        self.created_automatically = False
        self.created_date = datetime.now(timezone.utc)


class GuidelineTableReference(GuidelineReferenceBase):
    type: Literal[ReferenceType.TABLE] = Field(
        default=ReferenceType.TABLE, description="Reference type identifier for table references",
    )
    caption: str = Field(default="", description="Optional table caption or label")
    plain_text: str = Field(default="", description="Plain text content extracted from the table")
    table_markdown: str = Field(default="", description="Markdown representation of the table content")
    
    def extract_content(self) -> str:
        return (f"{self.caption}: " if self.caption else "") + self.table_markdown or self.plain_text or ""
    
    def update_content(self, new_content: str) -> None:
        self.plain_text = new_content
        self.table_markdown = new_content
        self.created_automatically = False
        self.created_date = datetime.now(timezone.utc)


class GuidelineRecommendationReference(GuidelineReferenceBase):
    type: Literal[ReferenceType.RECOMMENDATION] = Field(
        default=ReferenceType.RECOMMENDATION, description="Reference type identifier for recommendations",
    )
    recommendation_title: Optional[str] = Field(
        default=None, description="Optional heading or identifier of the recommendation", examples=["Empfehlung"],
    )
    recommendation_content: str = Field(
        description="Main textual content of the recommendation",
        examples=["Eine dreidimensionale Bildgebung (beispielsweise DVT/CT) kann indiziert sein ..."],
    )
    recommendation_grade: str = Field(
        description="Consensus or strength level of the recommendation (e.g., A, B, 0)",
        examples=["Starker Konsens (4/4, zwei Enthaltungen aufgrund eines Interessenskonfliktes)"],
    )
    
    def extract_content(self) -> str:
        return f"{self.recommendation_title}: " + self.recommendation_content + f"\n({self.recommendation_grade})"
    
    def update_content(self, new_content: str) -> None:
        self.recommendation_content = new_content
        self.created_automatically = False
        self.created_date = datetime.now(timezone.utc)


class GuidelineStatementReference(GuidelineReferenceBase):
    type: Literal[ReferenceType.STATEMENT] = Field(
        default=ReferenceType.STATEMENT,
        description="Reference type identifier for statement (similar to recommendation)",
    )
    statement_title: Optional[str] = Field(
        default=None, description="Optional heading or identifier of the statement", examples=["Statement"],
    )
    statement_content: str = Field(
        description="Main textual content of the statement",
        examples=[
            "Eine 3D-Bildgebung ist vor einer Weisheitszahnentfernung nicht erforderlich, wenn in der "
            "konventionell zweidimensionalen Bildgebung ...",
        ],
    )
    statement_consensus_grade: str = Field(
        description="Consensus or strength level of the statement",
        examples=["Starker Konsens (4/4, zwei Enthaltungen aufgrund eines Interessenskonfliktes)"],
    )
    
    def extract_content(self) -> str:
        return (f"{self.statement_title}: " if self.statement_title else "") + self.statement_content + (
            f"\n({self.statement_consensus_grade})" if self.statement_consensus_grade else "")
    
    def update_content(self, new_content: str) -> None:
        self.statement_content = new_content
        self.created_automatically = False
        self.created_date = datetime.now(timezone.utc)


class GuidelineMetadataReference(GuidelineReferenceBase):
    type: Literal[ReferenceType.METADATA] = Field(
        default=ReferenceType.METADATA, description="Reference type identifier for metadata entries",
    )
    metadata_type: str = Field(
        description="Type of metadata, such as 'title', 'authors', 'publication_date', etc.",
        examples=["validity_information"],
    )
    metadata_content: str = Field(
        description="Extracted text content of the metadata", examples=["Stand: August 2019; Gültig bis: August 2024"],
    )
    
    def extract_content(self) -> str:
        return self.metadata_content
    
    def update_content(self, new_content: str) -> None:
        self.metadata_content = new_content
        self.created_automatically = False
        self.created_date = datetime.now(timezone.utc)


class GuidelineReferenceChunkingRequest(BaseModel):
    source_reference_group_id: PyObjectId = Field(description="Reference group whose references should be copied and chunked")
    chunking_strategy: ChunkingStrategy = Field(description="How narrative text references should be split")
    target_reference_group_name: Optional[str] = Field(
        default=None,
        description="Optional name for the newly created target reference group. If omitted, a derived unique name is used.",
    )
    fixed_character_amount: Optional[int] = Field(
        default=None,
        ge=1,
        description="Required when chunking_strategy is 'fixed_characters'. Ignored for sentence and paragraph chunking.",
    )


class GuidelineReferenceChunkingUpdateRequest(BaseModel):
    source_reference_group_id: PyObjectId = Field(description="Reference group whose references should be copied and chunked")
    target_reference_group_id: PyObjectId = Field(description="Existing result reference group that should be updated")
    guideline_id: PyObjectId = Field(description="Guideline whose references in the target result group should be replaced")
    chunking_strategy: ChunkingStrategy = Field(description="How narrative text references should be split")
    fixed_character_amount: Optional[int] = Field(
        default=None,
        ge=1,
        description="Required when chunking_strategy is 'fixed_characters'. Ignored for sentence and paragraph chunking.",
    )


class GuidelineReferenceChunkingResult(BaseModel):
    target_reference_group_id: PyObjectId = Field(description="Reference group that received the chunked references")
    target_reference_group_name: str = Field(description="Resolved name of the target reference group")
    source_reference_group_id: PyObjectId = Field(description="Reference group used as source")
    processed_guideline_ids: List[PyObjectId] = Field(description="Guidelines whose references were copied into the result group")
    created_reference_ids: List[PyObjectId] = Field(description="IDs of the newly created references in the target group")
    deleted_reference_ids: List[str] = Field(
        default_factory=list,
        description="IDs removed from the target group before an update run. Empty for newly created chunk groups.",
    )
    chunking_strategy: ChunkingStrategy = Field(description="Applied chunking strategy")
    fixed_character_amount: Optional[int] = Field(
        default=None,
        description="Resolved fixed character amount if that strategy was selected",
    )
    source_reference_count: int = Field(description="Number of source references considered")
    created_reference_count: int = Field(description="Number of references inserted into the target group")
    chunked_text_reference_count: int = Field(description="Number of text references that resulted in more than one chunk")


class KeywordExtractionStrategy(str, Enum):
    YAKE = "yake"
    LLM = "llm"


class ReferenceKeywordSettings(BaseModel):
    strategy: KeywordExtractionStrategy = Field(
        default=KeywordExtractionStrategy.YAKE,
        description="Keyword extraction strategy used for each reference.",
    )
    language: str = Field("de", description="YAKE language code.")
    min_keywords: Optional[int] = Field(None, ge=1, description="Minimum number of keywords to target.")
    max_keywords: Optional[int] = Field(None, ge=1, description="Maximum number of keywords to keep before optional expansion.")
    max_n_gram_size: int = Field(3, ge=1, le=6, description="YAKE n-gram length.")
    deduplication_threshold: float = Field(0.9, ge=0.0, le=1.0, description="YAKE deduplication threshold.")
    ignore_terms: Optional[List[str]] = Field(None, description="Additional terms to ignore.")
    suppress_subphrases: bool = Field(True, description="Drop single terms that are contained in longer kept phrases.")
    headroom: int = Field(5, ge=0, le=50, description="Extra YAKE candidates to request.")
    llm_settings: Optional[LLMSettings] = Field(
        default=None,
        description="Required for LLM-based extraction and SNOMED expansion fallback.",
    )
    scope_description: Optional[str] = Field(None, description="Optional prompt scope override for LLM keyword extraction.")
    guidance_additions: Optional[List[str]] = Field(None, description="Optional extra prompt guidance for LLM keyword extraction.")
    important_terms: Optional[List[str]] = Field(None, description="Terms that should be emphasized in LLM extraction.")
    examples: Optional[List[Dict[str, Any]]] = Field(None, description="Few-shot examples for LLM extraction.")


class ReferenceKeywordExpansionSettings(BaseModel):
    enabled: bool = Field(False, description="Expand extracted keywords via SNOMED.")
    snomed_settings: SnomedSettings = Field(
        default_factory=SnomedSettings,
        description="SNOMED settings used when keyword expansion is enabled.",
    )
    allow_english_fallback: bool = Field(True, description="Allow English fallback during SNOMED synonym lookup.")
    include_original: bool = Field(True, description="Keep original extracted keywords alongside expanded synonyms.")


class ReferenceKeywordEnrichmentRequest(BaseModel):
    reference_id: Optional[PyObjectId] = Field(default=None, description="Single reference to enrich.")
    reference_group_id: Optional[PyObjectId] = Field(default=None, description="Reference group to enrich.")
    guideline_id: Optional[PyObjectId] = Field(
        default=None,
        description="Optional guideline restriction when enriching a whole reference group.",
    )
    keyword_settings: ReferenceKeywordSettings = Field(..., description="Keyword extraction settings.")
    expansion_settings: ReferenceKeywordExpansionSettings = Field(
        default_factory=ReferenceKeywordExpansionSettings,
        description="Optional SNOMED expansion settings.",
    )
    replace_existing: bool = Field(
        default=True,
        description="Replace `associated_keywords` instead of merging with any existing values.",
    )

    @model_validator(mode="after")
    def validate_target_combination(self):
        reference_id = self.reference_id
        reference_group_id = self.reference_group_id
        if bool(reference_id) == bool(reference_group_id):
            raise ValueError("Provide exactly one of reference_id or reference_group_id.")
        return self


class ReferenceKeywordUpdateRequest(BaseModel):
    keyword_settings: ReferenceKeywordSettings = Field(..., description="Keyword extraction settings.")
    expansion_settings: ReferenceKeywordExpansionSettings = Field(
        default_factory=ReferenceKeywordExpansionSettings,
        description="Optional SNOMED expansion settings.",
    )
    replace_existing: bool = Field(
        default=True,
        description="Replace `associated_keywords` instead of merging with any existing values.",
    )


class ReferenceGroupKeywordUpdateRequest(BaseModel):
    guideline_id: Optional[PyObjectId] = Field(
        default=None,
        description="Optional guideline restriction inside the selected reference group.",
    )
    keyword_settings: ReferenceKeywordSettings = Field(..., description="Keyword extraction settings.")
    expansion_settings: ReferenceKeywordExpansionSettings = Field(
        default_factory=ReferenceKeywordExpansionSettings,
        description="Optional SNOMED expansion settings.",
    )
    replace_existing: bool = Field(
        default=True,
        description="Replace `associated_keywords` instead of merging with any existing values.",
    )


class ReferenceKeywordEnrichmentItem(BaseModel):
    reference_id: PyObjectId = Field(description="Updated reference id.")
    extracted_keywords: List[str] = Field(description="Keywords extracted before SNOMED expansion.")
    stored_keywords: List[str] = Field(description="Keywords written to the reference.")


class ReferenceKeywordEnrichmentResult(BaseModel):
    processed_reference_count: int = Field(description="Number of references enriched.")
    skipped_reference_ids: List[str] = Field(default_factory=list, description="References skipped because no content/keywords were found.")
    references: List[ReferenceKeywordEnrichmentItem] = Field(description="Per-reference enrichment result.")


# ---- Polymorphic union for API routing / responses ----
GuidelineReference = Union[
    GuidelineTextReference,
    GuidelineImageReference,
    GuidelineTableReference,
    GuidelineRecommendationReference,
    GuidelineStatementReference,
    GuidelineMetadataReference,
]

# ---- Mapping for deserialization based on type ----
REFERENCE_TYPE_MAP = {
    ReferenceType.TEXT.value: GuidelineTextReference,
    ReferenceType.IMAGE.value: GuidelineImageReference,
    ReferenceType.TABLE.value: GuidelineTableReference,
    ReferenceType.RECOMMENDATION.value: GuidelineRecommendationReference,
    ReferenceType.STATEMENT.value: GuidelineStatementReference,
    ReferenceType.METADATA.value: GuidelineMetadataReference,
}
